language: php

dist: trusty

php:
    - '7.1.1'

services:
    - mysql

script:
    - phpunit

notification:
    slack:
        rooms: 
            - jobobagr:YmqvkAPUlhqRKEYXCgJ1qVQa#devops #to be created
        on_success: always #default : change
        on_failure: always #default : always