language: php

dist: trusty

php:
    - '7.1.1'

services:
    - mysql

before_script:
    - composer update

script:
    - phpunit

notifications:
    slack: jobobagr:haBu1Uoeo97A1iqKd2VEJLp3
    email: dliix66+udf40lxbnhknptlwfkko@boards.trello.com