language: php

dist: trusty

php:
    - '7.1.1'

services:
    - mysql

before_script:
    - composer update

script:
    - phpunit

notifications:
	email:
    	recipients:
    	  - dliix66+udf40lxbnhknptlwfkko@boards.trello.com
    	  - barat_v@epita.fr
    	  - r.nassty@gmail.com
    	on_success: always # default: change
    	on_failure: always # default: always
    slack: jobobagr:haBu1Uoeo97A1iqKd2VEJLp3